src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Test for the approval process</description>
        <label>Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_withAndWithoutSharing.cls
global without sharing class Test_withAndWithoutSharing {

	// system adm not Visible FLS with status__c 
	// Result : status__c still update succeed call by custom button
    webservice static String getOppyStatus() {
    	Opportunity testOppy = [SELECT Name, StageName, CloseDate, status__c, Approver1__c 
    								FROM Opportunity where id = '0067F00000CVSHf'];
    	System.debug(LoggingLevel.INFO, '*** testOppy: ' + testOppy);
    	System.debug(LoggingLevel.INFO, '*** testOppy.status__c: ' + testOppy.status__c);
    	testOppy.status__c = 'Submitted';
    	update testOppy;

    	return String.valueOf(testOppy.status__c);
    }
}